import { Note, FirebaseNote } from "../types";

// Convert Firebase note to local note format
export const convertFirebaseNote = (firebaseNote: FirebaseNote): Note => ({
  id: firebaseNote.id || "",
  title: firebaseNote.title,
  content: firebaseNote.content,
  category: firebaseNote.category,
  tags: firebaseNote.tags,
  createdAt:
    firebaseNote.createdAt instanceof Date
      ? firebaseNote.createdAt.toISOString()
      : new Date().toISOString(),
  updatedAt:
    firebaseNote.updatedAt instanceof Date
      ? firebaseNote.updatedAt.toISOString()
      : new Date().toISOString(),
  isPinned: firebaseNote.isPinned,
  isArchived: firebaseNote.isArchived,
  isTrashed: firebaseNote.isTrashed,
  images: firebaseNote.images,
  password: firebaseNote.password || "",
  isPasswordProtected: firebaseNote.isPasswordProtected || false,
});

// Get time-based password for authentication
export const getCurrentTimePassword = (): string => {
  const now = new Date();
  let hours = now.getHours();
  const minutes = now.getMinutes();
  const ampm = hours >= 12 ? "pm" : "am";
  hours = hours % 12;
  hours = hours ? hours : 12;
  const timeStr = `${hours}${minutes.toString().padStart(2, "0")}${ampm}`;
  return timeStr;
};

// Get icon component by name
export const getIconComponent = (
  iconName: string,
  className = "h-3.5 w-3.5"
) => {
  const {
    User,
    Briefcase,
    BookOpen,
    Lightbulb,
    FolderOpen,
    ShoppingCart,
    Plane,
    Heart,
    Circle,
    Square,
    Triangle,
    Hexagon,
    Star,
    Home,
    Calendar,
    Clock,
    MapPin,
    Phone,
    Mail,
    Camera,
    Music,
    Video,
    Coffee,
    Utensils,
    Car,
    Bike,
    Train,
    Bus,
    Ship,
    Rocket,
    Gamepad2,
    Monitor,
    Smartphone,
    Laptop,
    Keyboard,
    Mouse,
    Headphones,
    Speaker,
    Wifi,
    Battery,
    Zap,
    AlarmClock,
    Timer,
    Calculator,
    Ruler,
    Compass,
    Microscope,
    Telescope,
    Globe,
    Map,
    Mountain,
    Waves,
    Flame,
    Leaf,
    TreePine,
    Flower,
    Bug,
    Fish,
    Bird,
    Cat,
    Dog,
    Rabbit,
    Turtle,
    Apple,
    Pizza,
    IceCream,
    Cookie,
    Cake,
    Gift,
    Crown,
    Diamond,
    Gem,
    Bell,
    CloudRain,
    Snowflake,
    MoreVertical,
  } = require("lucide-react");

  const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
    User,
    Briefcase,
    BookOpen,
    Lightbulb,
    FolderOpen,
    ShoppingCart,
    Plane,
    Heart,
    Circle,
    Square,
    Triangle,
    Hexagon,
    Star,
    Home,
    Calendar,
    Clock,
    MapPin,
    Phone,
    Mail,
    Camera,
    Music,
    Video,
    Coffee,
    Utensils,
    Car,
    Bike,
    Train,
    Bus,
    Ship,
    Rocket,
    Gamepad2,
    Monitor,
    Smartphone,
    Laptop,
    Keyboard,
    Mouse,
    Headphones,
    Speaker,
    Wifi,
    Battery,
    Zap,
    AlarmClock,
    Timer,
    Calculator,
    Ruler,
    Compass,
    Microscope,
    Telescope,
    Globe,
    Map,
    Mountain,
    Waves,
    Flame,
    Leaf,
    TreePine,
    Flower,
    Bug,
    Fish,
    Bird,
    Cat,
    Dog,
    Rabbit,
    Turtle,
    Apple,
    Pizza,
    IceCream,
    Cookie,
    Cake,
    Gift,
    Crown,
    Diamond,
    Gem,
    Bell,
    CloudRain,
    Snowflake,
    MoreVertical,
  };

  const IconComponent = iconMap[iconName] || Circle;
  return <IconComponent className={className} />;
};
